import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignIn } from "@clerk/nextjs"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

      >
        <ClerkProvider>
          <SignedOut>
            <div className="min-h-screen min-w-screen flex justify-center items-center">
              <SignIn routing="hash" />
            </div>
          </SignedOut>
          <SignedIn>
            {children}
          </SignedIn>
        </ClerkProvider>
      </body>
    </html>
  );
}
